/**
 * OpenBook Composer - Typst Generator Engine
 * Converts Document IR into deterministic, high-quality Typst (.typ) markup.
 * Core Principle: LLM decides structure and intent. Typst decides geometry.
 */

import {
  DocumentIR,
  Block,
  Chapter,
  CalloutVariant,
  PaperSize
} from '../document/types';

/**
 * Maps paper size to Typst paper configuration name.
 */
function mapPaperSize(size: PaperSize): string {
  switch (size) {
    case 'A5':
      return 'a5';
    case 'Letter':
      return 'us-letter';
    case 'A4':
    default:
      return 'a4';
  }
}

/**
 * Maps CalloutVariant to background fill color and header icon title.
 */
function getCalloutStyle(variant: CalloutVariant): { fill: string; stroke: string; titleColor: string } {
  switch (variant) {
    case 'exam-tip':
      return { fill: 'rgb("f0fdf4")', stroke: 'rgb("16a34a")', titleColor: 'rgb("15803d")' }; // Emerald
    case 'important':
      return { fill: 'rgb("fef2f2")', stroke: 'rgb("dc2626")', titleColor: 'rgb("b91c1c")' }; // Red
    case 'remember':
      return { fill: 'rgb("f0f9ff")', stroke: 'rgb("0284c7")', titleColor: 'rgb("0369a1")' }; // Sky
    case 'common-mistake':
      return { fill: 'rgb("fff7ed")', stroke: 'rgb("ea580c")', titleColor: 'rgb("c2410c")' }; // Orange
    case 'shortcut':
    case 'formula':
      return { fill: 'rgb("faf5ff")', stroke: 'rgb("9333ea")', titleColor: 'rgb("7e22ce")' }; // Purple
    case 'summary':
    case 'note':
    default:
      return { fill: 'rgb("f8fafc")', stroke: 'rgb("475569")', titleColor: 'rgb("334155")' }; // Slate
  }
}

/**
 * Sanitizes text string for Typst.
 */
function sanitizeTypstText(text: string): string {
  if (!text) return '';
  // Escapes characters that have special meaning in Typst text mode if needed
  return text
    .replace(/\\/g, '\\\\')
    .replace(/#/g, '\\#')
    .replace(/\$/g, '\\$');
}

/**
 * Generates pure Typst source code from DocumentIR.
 */
export function generateTypstCode(docIR: DocumentIR): string {
  const meta = docIR.document;
  const page = meta.page;
  const paper = mapPaperSize(page.size);

  const lines: string[] = [];

  // 1. Page Configuration Setup
  lines.push(`// Generated by OpenBook Composer (Deterministic Typst Engine)`);
  lines.push(`#set page(`);
  lines.push(`  paper: "${paper}",`);
  lines.push(`  fill: rgb("${page.paperBgColor || '#ffffff'}"),`);
  lines.push(`  margin: (top: ${page.margin.top}mm, bottom: ${page.margin.bottom}mm, left: ${page.margin.left}mm, right: ${page.margin.right}mm),`);
  
  if (page.showPageNumbers) {
    lines.push(`  numbering: "1",`);
  }
  
  if (page.headerText) {
    lines.push(`  header: align(right)[#text(size: 8.5pt, fill: rgb("64748b"))[${sanitizeTypstText(page.headerText)}]],`);
  }
  
  if (page.footerText) {
    lines.push(`  footer: [`);
    lines.push(`    #line(length: 100%, stroke: 0.4pt + rgb("cbd5e1"))`);
    lines.push(`    #grid(`);
    lines.push(`      columns: (1fr, auto),`);
    lines.push(`      align(left)[#text(size: 8pt, fill: rgb("94a3b8"))[${sanitizeTypstText(page.footerText)}]],`);
    lines.push(`      align(right)[#text(size: 8pt, fill: rgb("94a3b8"))[Page #counter(page).display()]]`);
    lines.push(`    )`);
    lines.push(`  ],`);
  }
  lines.push(`)`);
  lines.push(``);

  // 2. Main Typography Setup
  const bodyFontName = page.bodyFont || page.themeFont || 'Libertinus Serif';
  const headingFontName = page.headingFont || page.themeFont || bodyFontName;
  const fontSize = page.bodyFontSize ? `${page.bodyFontSize}pt` : '10.5pt';
  const primaryHex = page.primaryColor || '#0369a1';

  lines.push(`#set text(font: "${bodyFontName}", size: ${fontSize}, fill: rgb("0f172a"))`);
  lines.push(`#set par(justify: true, leading: 0.55em)`);
  lines.push(`#set block(spacing: 0.65em)`);
  lines.push(`#show heading: set block(sticky: true)`);
  lines.push(`#show heading: set text(font: "${headingFontName}", fill: rgb("${primaryHex}"))`);
  lines.push(``);

  // 3. Optional Cover Page
  if (page.showCoverPage) {
    lines.push(`// --- Cover Page ---`);
    lines.push(`#align(center + horizon)[`);
    lines.push(`  #v(-2cm)`);
    lines.push(`  #text(size: 28pt, weight: "bold", fill: rgb("0369a1"))[${sanitizeTypstText(meta.title)}]`);
    if (meta.subtitle) {
      lines.push(`  #v(0.5cm)`);
      lines.push(`  #text(size: 16pt, style: "italic", fill: rgb("475569"))[${sanitizeTypstText(meta.subtitle)}]`);
    }
    lines.push(`  #v(1.5cm)`);
    lines.push(`  #line(length: 40%, stroke: 2pt + rgb("0284c7"))`);
    lines.push(`  #v(1.5cm)`);
    if (meta.author) {
      lines.push(`  #text(size: 13pt, weight: "medium", fill: rgb("334155"))[Author: ${sanitizeTypstText(meta.author)}]`);
    }
    if (meta.edition) {
      lines.push(`  #v(0.3cm)`);
      lines.push(`  #text(size: 11pt, fill: rgb("64748b"))[${sanitizeTypstText(meta.edition)}]`);
    }
    lines.push(`]`);
    lines.push(`#pagebreak()`);
    lines.push(``);
  }

  // 4. Table of Contents
  if (page.includeTOC) {
    lines.push(`// --- Table of Contents ---`);
    lines.push(`#outline(title: [Table of Contents], indent: 1.5em)`);
    lines.push(`#pagebreak()`);
    lines.push(``);
  }

  // 5. Chapters Rendering
  docIR.chapters.forEach((chapter, chIdx) => {
    if (chIdx > 0) {
      lines.push(`#pagebreak()`);
    }
    lines.push(`// --- Chapter ${chIdx + 1}: ${chapter.title} ---`);
    if (chapter.headerText) {
      lines.push(`#set page(header: align(right)[#text(size: 8.5pt, fill: rgb("64748b"))[${sanitizeTypstText(chapter.headerText)}]])`);
    }
    if (chapter.footerText) {
      lines.push(`#set page(footer: [#line(length: 100%, stroke: 0.4pt + rgb("cbd5e1")) #grid(columns: (1fr, auto), align(left)[#text(size: 8pt, fill: rgb("94a3b8"))[${sanitizeTypstText(chapter.footerText)}]], align(right)[#text(size: 8pt, fill: rgb("94a3b8"))[Page #counter(page).display()]])])`);
    }
    lines.push(`= ${sanitizeTypstText(chapter.title)}`);
    if (chapter.subtitle) {
      lines.push(`#text(size: 11pt, style: "italic", fill: rgb("64748b"))[${sanitizeTypstText(chapter.subtitle)}]`);
      lines.push(`#v(0.2cm)`);
    }

    chapter.blocks.forEach((block) => {
      lines.push(generateBlockTypst(block));
    });
  });

  return lines.join('\n');
}

/**
 * Translates an individual Block into Typst syntax.
 */
function generateBlockTypst(block: Block): string {
  const layout = block.layout || {};
  let content = '';

  switch (block.type) {
    case 'heading': {
      const equals = '='.repeat(block.level);
      content = `${equals} ${sanitizeTypstText(block.text)}`;
      break;
    }

    case 'paragraph': {
      content = sanitizeTypstText(block.text);
      break;
    }

    case 'list': {
      const itemsMarkup = block.items
        .map((item) => (block.ordered ? `+ ${sanitizeTypstText(item)}` : `- ${sanitizeTypstText(item)}`))
        .join('\n');
      content = itemsMarkup;
      break;
    }

    case 'table': {
      const colWidths = block.columns.map(() => '1fr').join(', ');
      const headerCells = block.columns.map((col) => `[*${sanitizeTypstText(col)}*]`).join(', ');
      const rowCells = block.rows
        .map((row) => row.map((cell) => `[${sanitizeTypstText(cell)}]`).join(', '))
        .join(',\n  ');

      let tableCode = `#table(\n  columns: (${colWidths}),\n  fill: (x, y) => if y == 0 { rgb("f1f5f9") } else if calc.even(y) { rgb("f8fafc") } else { none },\n  stroke: 0.5pt + rgb("cbd5e1"),\n  ${headerCells},\n  ${rowCells}\n)`;
      if (block.caption) {
        tableCode = `#figure(\n  ${tableCode},\n  caption: [${sanitizeTypstText(block.caption)}]\n)`;
      }
      content = tableCode;
      break;
    }

    case 'equation': {
      const expr = block.expression || '';
      let eqCode = `$ ${expr} $`;
      if (block.caption) {
        eqCode = `#figure(\n  ${eqCode},\n  caption: [${sanitizeTypstText(block.caption)}]\n)`;
      }
      content = eqCode;
      break;
    }

    case 'callout': {
      const style = getCalloutStyle(block.variant);
      const titleUpper = (block.title || block.variant.replace('-', ' ')).toUpperCase();
      content = `#block(
  fill: ${style.fill},
  stroke: 1pt + ${style.stroke},
  inset: 12pt,
  radius: 4pt,
  width: 100%,
  breakable: true,
  [
    #text(weight: "bold", fill: ${style.titleColor}, size: 9.5pt)[${sanitizeTypstText(titleUpper)}]
    #v(3pt)
    #text(size: 10pt)[${sanitizeTypstText(block.text)}]
  ]
)`;
      break;
    }

    case 'quote': {
      content = `#quote(block: true, attribution: [${sanitizeTypstText(block.author || '')}])[${sanitizeTypstText(block.text)}]`;
      break;
    }

    case 'image': {
      const width = layout.preferred_width || '80%';
      let imgCode = `#image("${block.src}", width: ${width})`;
      if (block.caption) {
        imgCode = `#figure(${imgCode}, caption: [${sanitizeTypstText(block.caption)}])`;
      }
      content = alignBlockContent(imgCode, layout.alignment);
      break;
    }

    case 'page_break': {
      content = `#pagebreak()`;
      break;
    }

    case 'spacer': {
      content = `#v(${block.height || '15pt'})`;
      break;
    }

    case 'horizontal_rule': {
      content = `#line(length: 100%, stroke: 0.5pt + rgb("cbd5e1"))`;
      break;
    }

    case 'mcq': {
      const optionsMarkup = block.options
        .map((opt) => {
          const isCorrectMark = opt.isCorrect ? ' *(Correct)*' : '';
          return `  #grid(columns: (24pt, 1fr), [*(${opt.label})*], [${sanitizeTypstText(opt.text)}${isCorrectMark}])`;
        })
        .join('\n#v(2pt)\n');

      let explanationMarkup = '';
      if (block.explanation) {
        explanationMarkup = `\n#v(4pt)\n#text(size: 9pt, fill: rgb("475569"), style: "italic")[*Explanation:* ${sanitizeTypstText(block.explanation)}]`;
      }

      content = `#block(
  fill: rgb("f8fafc"),
  stroke: 0.75pt + rgb("e2e8f0"),
  inset: 10pt,
  radius: 4pt,
  width: 100%,
  breakable: true,
  [
    #text(weight: "bold", size: 10.5pt)[Question:] ${sanitizeTypstText(block.question)}
    #v(6pt)
${optionsMarkup}${explanationMarkup}
  ]
)`;
      break;
    }

    case 'pyq': {
      content = `#block(
  fill: rgb("fffbeb"),
  stroke: 1pt + rgb("f59e0b"),
  inset: 10pt,
  radius: 4pt,
  width: 100%,
  breakable: true,
  [
    #text(weight: "bold", fill: rgb("b45309"), size: 9pt)[PYQ — ${sanitizeTypstText(block.examName)}]
    #v(3pt)
    #text(weight: "medium", size: 10pt)[${sanitizeTypstText(block.question)}]
    #v(4pt)
    #text(size: 9.5pt, fill: rgb("92400e"))[${sanitizeTypstText(block.answerText)}]
  ]
)`;
      break;
    }

    case 'quick_revision': {
      const bullets = block.bulletPoints.map((bp) => `- ${sanitizeTypstText(bp)}`).join('\n');
      content = `#block(
  fill: rgb("eff6ff"),
  stroke: 1pt + rgb("3b82f6"),
  inset: 12pt,
  radius: 4pt,
  width: 100%,
  breakable: true,
  [
    #text(weight: "bold", fill: rgb("1d4ed8"), size: 10pt)[⚡ ${sanitizeTypstText(block.title)}]
    #v(6pt)
    #text(size: 9.5pt)[
${bullets}
    ]
  ]
)`;
      break;
    }

    case 'mindmap': {
      content = `#block(
  fill: rgb("f8fafc"),
  stroke: 1pt + rgb("0284c7"),
  inset: 12pt,
  radius: 6pt,
  width: 100%,
  breakable: true,
  [
    #text(weight: "bold", fill: rgb("0369a1"), size: 10.5pt)[🌳 Concept MindMap — ${sanitizeTypstText(block.title)}]
    #v(6pt)
    #rect(width: 100%, fill: rgb("e0f2fe"), radius: 4pt, inset: 6pt)[*${sanitizeTypstText(block.rootNode?.label || block.title)}*]
  ]
)`;
      break;
    }

    case 'footnote': {
      content = `#footnote[${sanitizeTypstText(block.term)}: ${sanitizeTypstText(block.citationText)}]`;
      break;
    }

    default:
      content = `// Unknown block type`;
  }

  // Wrap in layout constraints if specified (avoiding unbreakable blocks for headings & tables)
  if (block.type !== 'heading' && block.type !== 'table') {
    if (layout.keep_with_next || layout.keep_together) {
      content = `#block(breakable: false)[${content}]`;
    }
  }

  return content;
}

function alignBlockContent(content: string, alignment?: 'left' | 'center' | 'right'): string {
  if (alignment === 'center') return `#align(center)[${content}]`;
  if (alignment === 'right') return `#align(right)[${content}]`;
  return content;
}
